const melee = [
  {
    name: "Fox",
    game_of_origin: "Star Fox",
    image: "../photos/Melee_fox.webp",
    alt_text: "Fox from Star Fox series in Super Smash Bros. Melee",
    tier: "S",
  },
  {
    name: "Falco",
    game_of_origin: "Star Fox",
    image: "../photos/Melee_falco.png",
    alt_text: "Falco from Star Fox series in Super Smash Bros. Melee",
    tier: "S",
  },
  {
    name: "Marth",
    game_of_origin: "Fire Emblem",
    image: "../photos/Melee_marth.png",
    alt_text: "Marth from Fire Emblem series in Super Smash Bros. Melee",
    tier: "S",
  },
  {
    name: "Sheik",
    game_of_origin: "The Legend of Zelda",
    image: "../photos/Melee_sheik.png",
    alt_text:
      "Sheik from The Legend of Zelda series in Super Smash Bros. Melee",
    tier: "A",
  },
  {
    name: "Peach",
    game_of_origin: "Super Mario",
    image: "../photos/Melee_peach.png",
    alt_text: "Peach from Super Mario series in Super Smash Bros. Melee",
    tier: "A",
  },
  {
    name: "Captain Falcon",
    game_of_origin: "F-Zero",
    image: "../photos/Melee_falcon.png",
    alt_text: "Captain Falcon from F-Zero series in Super Smash Bros. Melee",
    tier: "B",
  },
  {
    name: "Jigglypuff",
    game_of_origin: "Pokémon",
    image: "../photos/Melee_jigglypuff.webp",
    alt_text: "Jigglypuff from Pokémon series in Super Smash Bros. Melee",
    tier: "A",
  },
  {
    name: "Dr. Mario",
    game_of_origin: "Dr. Mario",
    image: "../photos/Melee_dr.mario.jpg",
    alt_text: "Dr. Mario from Dr. Mario series in Super Smash Bros. Melee",
    tier: "B",
  },
  {
    name: "Ice Climbers",
    game_of_origin: "Ice Climber",
    image: "../photos/Melee_icees.jpg",
    alt_text: "Ice Climbers from Ice Climber series in Super Smash Bros. Melee",
    tier: "B",
  },
  {
    name: "Link",
    game_of_origin: "The Legend of Zelda",
    image: "../photos/Melee_link.jpeg",
    alt_text: "Link from The Legend of Zelda series in Super Smash Bros. Melee",
    tier: "B",
  },
  {
    name: "Young Link",
    game_of_origin: "The Legend of Zelda",
    image: "../photos/Melee_yLink.jpg",
    alt_text:
      "Young Link from The Legend of Zelda series in Super Smash Bros. Melee",
    tier: "C",
  },
  {
    name: "Ganondorf",
    game_of_origin: "The Legend of Zelda",
    image: "../photos/Melee_ganondorf.webp",
    alt_text:
      "Ganondorf from The Legend of Zelda series in Super Smash Bros. Melee",
    tier: "C",
  },
  {
    name: "Samus",
    game_of_origin: "Metroid",
    image: "../photos/Melee_samus.png",
    alt_text: "Samus from Metroid series in Super Smash Bros. Melee",
    tier: "B",
  },
  {
    name: "Zelda",
    game_of_origin: "The Legend of Zelda",
    image: "../photos/Melee_zelda.jpg",
    alt_text:
      "Zelda from The Legend of Zelda series in Super Smash Bros. Melee",
    tier: "C",
  },
  {
    name: "Bowser",
    game_of_origin: "Super Mario",
    image: "../photos/Melee_bowser.png",
    alt_text: "Bowser from Super Mario series in Super Smash Bros. Melee",
    tier: "C",
  },
  {
    name: "Donkey Kong",
    game_of_origin: "Donkey Kong",
    image: "../photos/Melee_Donkey.webp",
    alt_text: "Donkey Kong from Donkey Kong series in Super Smash Bros. Melee",
    tier: "C",
  },
  {
    name: "Luigi",
    game_of_origin: "Super Mario",
    image: "../photos/Melee_luigi.webp",
    alt_text: "Luigi from Super Mario series in Super Smash Bros. Melee",
    tier: "C",
  },
  {
    name: "Mario",
    game_of_origin: "Super Mario",
    image: "../photos/Melee_mario.png",
    alt_text: "Mario from Super Mario series in Super Smash Bros. Melee",
    tier: "B",
  },
  {
    name: "Ness",
    game_of_origin: "EarthBound",
    image: "../photos/Melee_ness.webp",
    alt_text: "Ness from EarthBound series in Super Smash Bros. Melee",
    tier: "B",
  },
  {
    name: "Roy",
    game_of_origin: "Fire Emblem",
    image: "../photos/Melee_roy.webp",
    alt_text: "Roy from Fire Emblem series in Super Smash Bros. Melee",
    tier: "C",
  },
  {
    name: "Pichu",
    game_of_origin: "Pokémon",
    image: "../photos/Melee_pichu.webp",
    alt_text: "Pichu from Pokémon series in Super Smash Bros. Melee",
    tier: "D",
  },
  {
    name: "Yoshi",
    game_of_origin: "Super Mario",
    image: "../photos/Melee_yoshi.webp",
    alt_text: "Yoshi from Super Mario series in Super Smash Bros. Melee",
    tier: "B",
  },
  {
    name: "Kirby",
    game_of_origin: "Kirby",
    image: "../photos/Melee_kirby.webp",
    alt_text: "Kirby from Kirby series in Super Smash Bros. Melee",
    tier: "C",
  },
  {
    name: "Mewtwo",
    game_of_origin: "Pokémon",
    image: "../photos/Melee_mewtwo.png",
    alt_text: "Mewtwo from Pokémon series in Super Smash Bros. Melee",
    tier: "B",
  },
  {
    name: "Mr. Game & Watch",
    game_of_origin: "Game & Watch",
    image: "../photos/Melee_gnw.jpeg",
    alt_text:
      "Mr. Game & Watch from Game & Watch series in Super Smash Bros. Melee",
    tier: "B",
  },
  {
    name: "Pikachu",
    game_of_origin: "Pokémon",
    image: "../photos/Melee_pikachu.webp",
    alt_text: "Pikachu from Pokémon series in Super Smash Bros. Melee",
    tier: "A",
  },
];

export { melee };
