const donuts = [
  {
    name: "Classic Glazed",
    price: 1.5,
    flavor: "Sweet vanilla glaze",
    alt: "Classic glazed donut",
    image: "",
  },
  {
    name: "Chocolate Frosted",
    price: 1.75,
    flavor: "Rich chocolate icing",
    alt: "Chocolate frosted donut",
    image: "",
  },
  {
    name: "Maple Bar",
    price: 2.0,
    flavor: "Maple syrup glaze",
    alt: "Maple bar donut",
    image: "",
  },
  {
    name: "Strawberry Frosted",
    price: 1.75,
    flavor: "Strawberry icing with sprinkles",
    alt: "Strawberry frosted donut",
    image: "",
  },
  {
    name: "Boston Cream",
    price: 2.25,
    flavor: "Custard filled with chocolate topping",
    alt: "Boston cream donut",
    image: "",
  },
  {
    name: "Powdered Sugar",
    price: 1.5,
    flavor: "Soft donut dusted with powdered sugar",
    alt: "Powdered sugar donut",
    image: "",
  },
  {
    name: "Cinnamon Sugar",
    price: 1.5,
    flavor: "Cinnamon and sugar coating",
    alt: "Cinnamon sugar donut",
    image: "",
  },
  {
    name: "Lemon Filled",
    price: 2.0,
    flavor: "Lemon cream filling",
    alt: "Lemon filled donut",
    image: "",
  },
  {
    name: "Red Velvet",
    price: 2.5,
    flavor: "Red velvet cake with cream cheese icing",
    alt: "Red velvet donut",
    image: "",
  },
  {
    name: "Coffee Glazed",
    price: 1.75,
    flavor: "Coffee glaze with a hint of vanilla",
    alt: "Coffee glazed donut",
    image: "",
  },
  {
    name: "Bavarian Cream",
    price: 2.25,
    flavor: "Bavarian cream filling with chocolate topping",
    alt: "Bavarian cream donut",
    image: "",
  },
  {
    name: "S'mores",
    price: 2.5,
    flavor: "Chocolate, marshmallow, and graham cracker",
    alt: "S'mores donut",
    image: "",
  },
  {
    name: "Maple Bacon",
    price: 2.75,
    flavor: "Maple glaze with crispy bacon bits",
    alt: "Maple bacon donut",
    image: "",
  },
  {
    name: "Nutella Filled",
    price: 2.5,
    flavor: "Nutella cream filling",
    alt: "Nutella filled donut",
    image: "",
  },
  {
    name: "Pistachio",
    price: 2.5,
    flavor: "Pistachio icing with crushed pistachios",
    alt: "Pistachio donut",
    image: "",
  },
  {
    name: "Raspberry Jelly",
    price: 1.75,
    flavor: "Raspberry jelly filling with powdered sugar",
    alt: "Raspberry jelly donut",
    image: "",
  },
  {
    name: "Churro",
    price: 2.0,
    flavor: "Cinnamon sugar churro style",
    alt: "Churro donut",
    image: "",
  },
  {
    name: "Cookies and Cream",
    price: 2.5,
    flavor: "Chocolate and cream with cookie bits",
    alt: "Cookies and cream donut",
    image: "",
  },
  {
    name: "Birthday Cake",
    price: 2.25,
    flavor: "Cake batter with colorful sprinkles",
    alt: "Birthday cake donut",
    image: "",
  },
  {
    name: "Mango Glazed",
    price: 2.0,
    flavor: "Mango glaze with tropical notes",
    alt: "Mango glazed donut",
    image: "",
  },
];
